//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int category_ID { get; set; }
        public int adminLogin_ID { get; set; }
        public Nullable<int> subcategory_ID { get; set; }
        public string name { get; set; }
    }
}
