//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBilling
    {
        public int customerBilling_ID { get; set; }
        public int cardType { get; set; }
        public string cardNumber { get; set; }
        public System.DateTime expireDate { get; set; }
        public int customer_ID { get; set; }
    }
}
