//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    
    public partial class CustomerAddress
    {
        public CustomerAddress(){}

        public int customerAddress_ID { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }

        public static CustomerAddress ConvertToProperty(DataRow dr)
        {
            CustomerAddress _customerAddress = new CustomerAddress();
            _customerAddress.customerAddress_ID = Convert.ToInt32(dr["customerAddress_ID"]);
            _customerAddress.address1 = dr["address1"].ToString();
            _customerAddress.address2 = dr["address2"].ToString();
            _customerAddress.city = dr["city"].ToString();
            _customerAddress.state = dr["state"].ToString();
            _customerAddress.zip = dr["zip"].ToString();
            return _customerAddress;
        }
    }
}
