//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    using System.Security.Cryptography;
    using System.Web.Security;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class Customer
    {
        public int customer_ID { get; set; }
    
        public string firstName { get; set; }
  
        public string lastName { get; set; }
       
        public string email { get; set; }

        public string phone { get; set; }

        
    }
}
