//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
using System.Data;

    public partial class Customer
    {
        public Customer(){}

        public int customer_ID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public static Customer ConvertToProperty(DataRow dr)
        {
            Customer _customer = new Customer();
            _customer.customer_ID = Convert.ToInt32(dr["customer_ID"]);
            _customer.firstName = dr["firstName"].ToString();
            _customer.lastName = dr["lastName"].ToString();
            _customer.email = dr["email"].ToString();
            _customer.phone = dr["phone"].ToString();
            return _customer;
        }
    }
}
