//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int order_ID { get; set; }
        public int customer_ID { get; set; }
        public int shippingAddress_ID { get; set; }
        public int customerBilling_ID { get; set; }
        public int orderDetails_ID { get; set; }
        public int orderStatus_ID { get; set; }
        public int shippingMethod_ID { get; set; }
        public System.DateTime orderDate { get; set; }
        public decimal tax { get; set; }
        public decimal grandTotal { get; set; }
    }
}
